name: Documentation pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install doxygen
        run: cd build && 
              wget https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz && 
              tar -xvf doxygen-1.9.5.linux.bin.tar.gz && 
              cd .. &&
              chmod +x ./build/doxygen-1.9.5/bin/doxygen &&
              alias doxygen="./build/doxygen-1.9.5/bin/doxygen"
        # run: git clone https://github.com/doxygen/doxygen.git && cd doxygen && mkdir build && cd build && cmake -G "Unix Makefiles" .. && make && make install && cd ../..
      - name: Submodules
        run: git submodule update --init --recursive 
      - name: Generate documentation
        run: doxygen
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
