name: Release

on:
  # Run pushes for tags beginning with v {git tag v0.0.1 && git push origin v0.0.1}
  push:
    tags:
      - "v*"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      # Windows X86_64 - GCC
      - name: MinGW X86_64 Build
        run: |
          make G=Ninja
          make test
          make pkg NAME="fennet-windows-x86_64-mingw"
          make clean
      - name: MSVC X86_64 Build
        run: |
          make G=Ninja CC=clang CXX=clang++
          make test
          make pkg NAME="fennet-windows-x86_64-msvc"
          make clean
      - uses: actions/upload-artifact@master
        with:
          name: windows-artifact
          path: packaged
  linux:
    needs: windows
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: windows-artifact
          path: packaged
      - name: Build step
        run: make
      - name: Test step
        run: make test
      - name: Package build artifacts
        run:  make pkg NAME="linux-gcc"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Test Release"
          files: |
            LICENSE
            packaged/*