name: Release

on:
  # Run pushes for tags beginning with v {git tag v0.0.1 && git push origin v0.0.1}
  push:
    tags:
      - "v*"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 

jobs:
  windows:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      - name: MinGW X86_64 Build
        run: |
          make G=Ninja
          make test
          make pkg NAME="fennet-windows-x86_64-mingw"
          make clean
      - name: MinGW X86_32 Build
        run: |
          make G=Ninja CMAKE_FLAGS="-DCMAKE_C_COMPILER_ARG1=-m32 -DCMAKE_CXX_COMPILER_ARG1=-m32"
          make test
          make pkg NAME="fennet-windows-x86_32-mingw"
          make clean
      - name: MSVC X86_64 Build
        run: |
          make G=Ninja CC=clang CXX=clang++
          make test
          make pkg NAME="fennet-windows-x86_64-msvc"
          make clean
      - name: MSVC X86_32 Build
        run: |
          make G=Ninja CMAKE_FLAGS="-DCMAKE_C_COMPILER_ARG1=-m32 -DCMAKE_CXX_COMPILER_ARG1=-m32" CC=clang CXX=clang++
          make test
          make pkg NAME="fennet-windows-x86_32-msvc"
          make clean
      - uses: actions/upload-artifact@master
        with:
          name: windows-artifact
          path: packaged
  linux:
    needs: windows
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: windows-artifact
          path: packaged
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: windows-artifact
      - name: GCC X86_64 Build
        run: |
          make
          make test
          make pkg NAME="fennet-linux-x86_64-gcc"
          make clean
      - name: GCC X86_32 Build
        run: |
          make CMAKE_FLAGS="-DCMAKE_C_COMPILER_ARG1=-m32 -DCMAKE_CXX_COMPILER_ARG1=-m32"
          make test
          make pkg NAME="fennet-linux-x86_32-gcc"
          make clean
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Test Release"
          files: |
            LICENSE
            packaged/*