name: Release

on:
  # Run pushes for tags beginning with v {git tag v0.0.1 && git push origin v0.0.1}
  push:
    tags:
      - "v*"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Build step
        run: make
      - name: Test step
        run: make test
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            build/*.so
            build/*.a
            build/*.dll
            build/*.lib