name: Release

on:
  # Run pushes for tags beginning with v {git tag v0.0.1 && git push origin v0.0.1}
  push:
    tags:
      - "v*"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Build step
        run: make
      - name: Test step
        run: make test
      - name: Package build artifacts
        run: mkdir gh_windows_artifacts &&
              copy build\*.dll gh_windows_artifacts &&
              copy build\*.lib gh_windows_artifacts &&
              copy build\*.a gh_windows_artifacts &&
              copy build\*.so gh_windows_artifacts
      - uses: actions/upload-artifact@master
        with:
          name: windows-artifact
          path: gh_windows_artifacts
  linux:
    needs: windows
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: windows-artifact
          path: gh_windows_artifacts
      - name: Build step
        run: make
      - name: Test step
        run: make test
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Test Release"
          files: |
            LICENSE
            build/*.so
            build/*.a
            build/*.dll
            build/*.lib
            gh_windows_artifacts/*.so
            gh_windows_artifacts/*.a
            gh_windows_artifacts/*.dll
            gh_windows_artifacts/*.lib